// ==========================================
// Games/Sql.js
// The SQL a new game needs, written by the site rather than by
// hand.
//
// Public exports:
//   slug(value)                       -> a safe game id
//   namesFor(gameId)                  -> binding / database / env names
//   gameSchemaSql(gameId, options)    -> the game's own D1 schema
//   settingsSeedSql(gameId, settings) -> an override row, as SQL
//   productSeedSql(gameId, ...)       -> product overrides, as SQL
//   purgeSeedSql(gameId)              -> the DELETEs that clear both
//   schemaRepairSql(report)           -> the ALTER TABLEs for a
//                                        game_settings that is behind
//   wranglerSnippet(gameId)           -> the d1_databases entry
//   setupCommands(gameId, options)    -> the wrangler commands, in order
//
// It does not execute anything. Not against D1, not against
// anything. The output is text on a page with a copy button.
// ==========================================

import { PRODUCT_KIND } from '../Config.js'


// ==========================================
// slug
// A game id that is safe everywhere it has to appear.
// ==========================================
export function slug(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40)
}


// ==========================================
// namesFor
// Every name derived from one game id.
// ==========================================
export function namesFor(gameId) {
  const id = slug(gameId)
  const upper = id.replace(/-/g, '_').toUpperCase()

  return {
    id,
    upper,
    binding: `${upper}_DB`,
    database: `${id}-db`,
    // The Pascal-case form used for a Unity namespace and for
    // the default package name.
    pascal: id.split('-').filter(Boolean).map(part => part[0].toUpperCase() + part.slice(1)).join(''),
    env: {
      android: `${upper}_GOOGLE_CLIENT_ID_ANDROID`,
      web: `${upper}_GOOGLE_CLIENT_ID_WEB`,
      secret: `${upper}_GOOGLE_CLIENT_SECRET`,
      deepLinkScheme: `${upper}_DEEPLINK_SCHEME`
    }
  }
}


// ==========================================
// gameSchemaSql
// One game's own database, complete.
// ==========================================
export function gameSchemaSql(gameId, {
  gameName = '',
  withPurchases = true,
  withSessions = false,
  withSeed = false
} = {}) {
  const names = namesFor(gameId)
  const title = gameName || names.pascal
  const at = new Date().toISOString().slice(0, 10)

  const head = `-- ==========================================
-- ${names.database}
-- The player database for ${title}.
--
-- Generated by the TheGod panel on ${at}.
-- Review it before you run it. Nothing on the site executes
-- this file - that is on purpose, and this comment is the
-- moment it buys you.
--
-- Apply with:
--   npx wrangler d1 create ${names.database}
--   (copy the printed database_id into wrangler.jsonc)
--   npx wrangler d1 execute ${names.database} --remote --file=./migrations/${names.id}.sql
--
-- Every statement is CREATE ... IF NOT EXISTS, so running it
-- twice is a no-op rather than an error.
--
-- Bound in wrangler.jsonc as "${names.binding}", which is the
-- name GAME_REGISTRY['${names.id}'].d1Binding must contain. If
-- those two strings ever disagree, every data endpoint for this
-- game answers "db_not_bound" and nothing else breaks - which
-- is a confusing hour, so they are worth checking first.
-- ==========================================


-- ==========================================
-- players
-- One row per person who has signed in.
--
-- THE COLUMN NAMES BELOW ARE A CONTRACT. worker.js reads them
-- by name in handleDatabaseGet, handleDatabaseSet and
-- handleDatabasePatch, and pages/leaderboard.js reads
-- username / high_score / profile_pic_url. Renaming one here
-- does not produce an error anywhere - it produces a game whose
-- saves quietly stop working.
--
-- The row is created at first sign-in and updated from then on.
-- Nothing deletes it: a player who uninstalls and comes back
-- next year still owns their score.
-- ==========================================
CREATE TABLE IF NOT EXISTS players (
  -- The local part of the Google address, lowercased and cut to
  -- fifteen characters - the same derivation the Worker makes
  -- in playerIdFromEmail(). Short, stable, and readable in a
  -- support thread, which a Google subject id is not.
  player_id       TEXT PRIMARY KEY,

  email           TEXT NOT NULL,

  -- 3-12 characters, English letters and digits only, checked
  -- against a profanity blocklist by validateUsername() in
  -- worker.js before it ever reaches this column.
  username        TEXT,

  profile_pic_url TEXT,

  -- The leaderboard's sort key. Only ever moves up: the write
  -- path refuses a score that is not higher than the one
  -- already here, so a replayed or tampered submission cannot
  -- lower somebody's record.
  high_score      INTEGER NOT NULL DEFAULT 0,

  games_played    INTEGER NOT NULL DEFAULT 0,
  total_play_time INTEGER NOT NULL DEFAULT 0,

  -- Cosmetics the game owns the meaning of. selected_color is a
  -- bare hex string ('FFFFFF'); the two purchased_* columns are
  -- JSON, read with a fallback so a malformed value is an empty
  -- inventory rather than a 500.
  selected_color  TEXT NOT NULL DEFAULT 'FFFFFF',
  purchased_colors TEXT NOT NULL DEFAULT '["FFFFFF"]',
  purchased_items  TEXT NOT NULL DEFAULT '{}',

  -- Anything else THIS game wants to save.
  --
  -- A JSON object the Worker stores, merges and never inspects.
  -- The columns above are the ones this side reads by name - the
  -- leaderboard needs high_score, the account page needs
  -- total_play_time - and this is for everything it does not
  -- need to understand.
  --
  -- That is what keeps a new game from needing a schema change:
  -- levelsCompleted, an inventory, unlocked characters, a
  -- difficulty setting - all of it is a key in here rather than
  -- a column, a Worker mapping and a C# field.
  --
  --   PATCH  { "dataPatch": { "levelsCompleted": 12 } }   merges
  --   POST   { "data":      { ... whole document ... } }  replaces
  data_json        TEXT NOT NULL DEFAULT '{}',

  created_at      INTEGER NOT NULL,
  last_login      INTEGER,

  -- Moderation. NULL everywhere means an ordinary account.
  --
  -- banned_at is permanent until lifted; restricted_until is the
  -- time-boxed version and needs no clearing, because a value in
  -- the past is simply not a restriction. The state shown in the
  -- panel is derived from these two, so there is no third column
  -- that can disagree with them.
  --
  -- worker.js reads banned_at on every score submission and both
  -- leaderboard queries. A game whose table lacks these columns
  -- still works - every check falls back to "not banned" - which
  -- is what migrations/0006_player_moderation.sql exists to fix
  -- for games created before this block did.
  banned_at        INTEGER,
  ban_reason       TEXT,
  restricted_until INTEGER,
  restrict_reason  TEXT,
  admin_note       TEXT,

  -- The player's own decision about the public board.
  --
  -- 1 keeps them off it entirely: no score, no name, no picture,
  -- and no gap in the ranking where they used to be. Set from
  -- the account page at /${names.id}/account, and readable and
  -- writable by the game client as \`leaderboardOptOut\` on the
  -- profile endpoints, so a switch inside the game and the
  -- checkbox on the site are the same setting.
  --
  -- NULL and 0 both mean listed. Opting out has to be an act, so
  -- the absence of a decision is not one.
  --
  -- This is a visibility flag and nothing else. The score is
  -- still recorded, the account page still shows it, and turning
  -- it back off restores the player at whatever rank that score
  -- earns. It is deliberately NOT part of the moderation block
  -- above: those are things done TO a player and this is a thing
  -- done BY one.
  leaderboard_opt_out INTEGER
);

-- The leaderboard query, which is the only hot read in this
-- database: ORDER BY high_score DESC LIMIT n, run on every
-- board view.
CREATE INDEX IF NOT EXISTS idx_players_score ON players (high_score DESC);
CREATE INDEX IF NOT EXISTS idx_players_email ON players (email);

-- The board query is "highest scores, excluding banned and
-- excluding anybody who opted out", so the index carries all
-- three columns in the order the WHERE clause narrows them.
CREATE INDEX IF NOT EXISTS idx_players_board
  ON players (banned_at, leaderboard_opt_out, high_score DESC);`

  const purchases = `


-- ==========================================
-- player_purchases
-- This game's own copy of what a player owns.
--
-- The authoritative record lives in the licence database's
-- game_entitlements table, which is what
-- GET /games/${names.id}/entitlements reads. This table is a
-- mirror, and it exists for one reason: a game that has to make
-- a network call before it can draw the shop is a game that
-- shows a spinner on a train.
--
-- Written when the client syncs, read freely, and never trusted
-- over the entitlements API when the two disagree - the API is
-- the side that saw the money.
-- ==========================================
CREATE TABLE IF NOT EXISTS player_purchases (
  player_id   TEXT NOT NULL,

  -- The catalogue id from GAME_REGISTRY['${names.id}'].store,
  -- not the Google Play sku. The two are allowed to differ and
  -- usually do.
  product_id  TEXT NOT NULL,

  -- 'consumable' | 'nonconsumable' | 'pass'
  kind        TEXT NOT NULL DEFAULT 'nonconsumable',

  -- Unspent balance for a consumable; 1 for anything owned
  -- outright.
  quantity    INTEGER NOT NULL DEFAULT 0,

  -- 'web' (bought on the site), 'in-app' (bought in the store),
  -- 'grant' (given by an operator).
  source      TEXT NOT NULL DEFAULT 'web',

  expires_at  INTEGER,
  synced_at   INTEGER NOT NULL,

  PRIMARY KEY (player_id, product_id),
  FOREIGN KEY (player_id) REFERENCES players (player_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_purchases_player ON player_purchases (player_id);`

  const sessions = `


-- ==========================================
-- play_sessions
-- One row per run, for playtime and retention.
--
-- Optional, and genuinely optional: nothing in the Worker reads
-- it. It is here because total_play_time on the players table
-- is a single number that can only ever answer "how long", and
-- the questions that follow the first week are all "when" and
-- "how often".
--
-- Rows are cheap and numerous. Prune them on a schedule if this
-- game gets busy - the aggregate on players survives the prune.
-- ==========================================
CREATE TABLE IF NOT EXISTS play_sessions (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id  TEXT NOT NULL,
  started_at INTEGER NOT NULL,
  ended_at   INTEGER,
  duration   INTEGER NOT NULL DEFAULT 0,
  score      INTEGER NOT NULL DEFAULT 0,
  app_version TEXT
);

CREATE INDEX IF NOT EXISTS idx_sessions_player ON play_sessions (player_id, started_at);`

  const seed = `


-- ==========================================
-- A row to prove the table works.
--
-- Delete it once you have seen it on the leaderboard. It is
-- here because "did the migration run?" is otherwise answered
-- by an empty table, which looks exactly like a migration that
-- did not.
-- ==========================================
INSERT OR IGNORE INTO players
  (player_id, email, username, high_score, games_played, created_at, last_login)
VALUES
  ('demo', 'demo@example.com', 'DemoPlayer', 1, 1, ${Date.now()}, ${Date.now()});`

  return head
    + (withPurchases ? purchases : '')
    + (withSessions ? sessions : '')
    + (withSeed ? seed : '')
    + '\n'
}


// ==========================================
// sqlText
// A string literal SQLite will accept.
// ==========================================
function sqlText(value) {
  if (value === null || value === undefined || value === '') return 'NULL'
  return "'" + String(value).replace(/'/g, "''") + "'"
}


// ==========================================
// sqlExact
// The same, except that an empty string stays an empty string.
//
// For `badge`, which has THREE states and not two: NULL means
// "no override, use the catalogue" and '' means "the operator
// chose No ribbon". Games/Registry.js is careful about that
// distinction on read - collapsing the two there was a visible
// bug once - and a generator that collapses them on write undoes
// it: pasting the output into a second deployment would put the
// "best value" ribbon back on a product somebody had removed it
// from.
// ==========================================
function sqlExact(value) {
  if (value === null || value === undefined) return 'NULL'
  return "'" + String(value).replace(/'/g, "''") + "'"
}


// ==========================================
// settingsSeedSql
// The current overrides, as a statement somebody can run on
// another deployment.
//
// The point is a staging site and a live one that look the
// same. Without this, matching them means retyping every field
// into a second panel and hoping.
// ==========================================
export function settingsSeedSql(gameId, settings = {}, options = {}) {
  const id = slug(gameId)

  // The row's OWN timestamp, not this moment.
  //
  // This used to be Date.now(), which made the block a lie in the
  // one way that matters: it is titled "as they stand right now"
  // and is read to answer "what is actually stored?". A timestamp
  // invented at render time meant the SQL and the table disagreed
  // about when the row was last touched, and pasting it into
  // another deployment silently marked every field as edited
  // today. A row that has never been written has no timestamp of
  // its own, and only then is now() the honest answer.
  const at = Number(settings.updated_at) || Date.now()

  // Columns this database does not have. Named separately below
  // rather than left out silently: "there is no value" and "there
  // is nowhere to put a value" are different states, and only one
  // of them is fixed by typing something into the panel.
  const missing = new Set(Array.isArray(options.missingColumns) ? options.missingColumns : [])

  const columns = [
    ['display_name', sqlText(settings.display_name)],
    ['logo_url', sqlText(settings.logo_url)],
    ['accent_color', sqlText(settings.accent_color)],
    ['desc_fa', sqlText(settings.desc_fa)],
    ['desc_en', sqlText(settings.desc_en)],
    ['desc_ja', sqlText(settings.desc_ja)],
    ['tags_json', sqlText(settings.tags_json)],
    ['status', sqlText(settings.status)],
    ['download_enabled', settings.download_enabled === null || settings.download_enabled === undefined
      ? 'NULL'
      : (Number(settings.download_enabled) ? '1' : '0')],
    ['download_json', sqlText(settings.download_json)],
    ['min_version', sqlText(settings.min_version)],
    ['note', sqlText(settings.note)],
    ['deeplink_scheme', sqlText(settings.deeplink_scheme)],

    // The landing page (0005 and 0008). Carried across with
    // everything else, because a staging site that matches the
    // live one on prices and not on its screenshots is not a
    // staging site - it is a second game page to maintain.
    ['hero_url', sqlText(settings.hero_url)],
    ['videos_json', sqlText(settings.videos_json)],
    ['devices_json', sqlText(settings.devices_json)],
    ['about_fa', sqlText(settings.about_fa)],
    ['about_en', sqlText(settings.about_en)],
    ['about_ja', sqlText(settings.about_ja)],
    ['tagline_fa', sqlText(settings.tagline_fa)],
    ['tagline_en', sqlText(settings.tagline_en)],
    ['tagline_ja', sqlText(settings.tagline_ja)],
    ['features_json', sqlText(settings.features_json)],
    ['screenshots_json', sqlText(settings.screenshots_json)],
    ['faq_json', sqlText(settings.faq_json)],

    // The per-language galleries and the Google disclosure (0011).
    // Same reasoning as the block above, and one more: a game
    // whose Japanese screenshots exist only on the live site is a
    // game nobody can test a layout change against.
    ['screenshots_fa_json', sqlText(settings.screenshots_fa_json)],
    ['screenshots_en_json', sqlText(settings.screenshots_en_json)],
    ['screenshots_ja_json', sqlText(settings.screenshots_ja_json)],
    ['videos_fa_json', sqlText(settings.videos_fa_json)],
    ['videos_en_json', sqlText(settings.videos_en_json)],
    ['videos_ja_json', sqlText(settings.videos_ja_json)],

    // Carried as 1/0/NULL rather than through sqlText, for the
    // reason download_enabled above is: this is a switch, and
    // "off" is a decision that has to survive the copy. A seed
    // that dropped a 0 would put a disclosure back on a game
    // somebody had deliberately taken it off.
    ['google_enabled', settings.google_enabled === null || settings.google_enabled === undefined
      ? 'NULL'
      : (Number(settings.google_enabled) ? '1' : '0')],
    ['google_head_fa', sqlText(settings.google_head_fa)],
    ['google_head_en', sqlText(settings.google_head_en)],
    ['google_head_ja', sqlText(settings.google_head_ja)],
    ['google_body_fa', sqlText(settings.google_body_fa)],
    ['google_body_en', sqlText(settings.google_body_en)],
    ['google_body_ja', sqlText(settings.google_body_ja)]
  ]

  // Only the columns that are actually SET are named. Two
  // reasons, and the second is the one that bites: naming a NULL
  // column adds nothing, and naming a column the target database
  // does not have yet fails the whole statement over a field that
  // was empty anyway.
  const set = columns.filter(([, value]) => value !== 'NULL')

  // What is empty, split by WHY it is empty. A column that is
  // NULL is a decision - "no override, use Config.js". A column
  // that is not in the table is not a decision at all: the panel
  // cannot write it, and anybody reading a block that showed the
  // two identically would conclude they had simply not filled
  // that field in yet.
  const unset = columns
    .filter(([name, value]) => value === 'NULL' && !missing.has(name))
    .map(([name]) => name)
  const absent = columns.filter(([name]) => missing.has(name)).map(([name]) => name)

  const absentNote = absent.length
    ? `--\n`
      + `-- NOT IN THIS DATABASE (${absent.length}): ${wrapList(absent)}\n`
      + `-- These columns do not exist in game_settings here, so the panel\n`
      + `-- cannot write them and nothing you type into those fields will\n`
      + `-- be kept. Run the repair on this tab to add them.\n`
    : ''

  if (!set.length) {
    return `-- '${id}' has no overrides stored.\n`
         + `--\n`
         + (options.exists
              ? `-- The game_settings row exists and every column in it is NULL,\n`
              : `-- There is no game_settings row for '${id}' at all,\n`)
         + `-- which means the site is showing exactly what GAME_REGISTRY in\n`
         + `-- Config.js says - the name, the logo, the colour, the\n`
         + `-- descriptions, the landing page, all of it.\n`
         + absentNote
         + `--\n`
         + `-- There is nothing to copy to another deployment: a row of\n`
         + `-- NULLs and no row at all render identically. If you want the\n`
         + `-- empty row gone, this is the statement that does it, and the\n`
         + `-- panel writes a fresh one the next time you press save.\n`
         + `--\n`
         + `-- DELETE FROM game_settings WHERE game_id = ${sqlText(id)};\n`
  }

  const names = set.map(([name]) => name)

  return `-- Overrides for '${id}', as they stand right now.
-- Safe to re-run: the ON CONFLICT clause updates in place.
--
-- ${set.length} column${set.length === 1 ? '' : 's'} overridden. Everything not named below is
-- "no override" and comes from Config.js.
--
-- updated_at is the row's own timestamp (${new Date(at).toISOString()}),
-- not the moment this was generated - so pasting this elsewhere
-- reproduces the state, including when it was last changed.
${unset.length ? `--\n-- NO OVERRIDE (${unset.length}): ${wrapList(unset)}\n` : ''}${absentNote}INSERT INTO game_settings
  (game_id, ${names.join(', ')}, updated_at)
VALUES (
  ${sqlText(id)},
${set.map(([, value]) => `  ${value}`).join(',\n')},
  ${at}
)
ON CONFLICT (game_id) DO UPDATE SET
${names.map(name => `  ${name} = excluded.${name}`).join(',\n')},
  updated_at = excluded.updated_at;
`
}


// A long list of column names, wrapped so a comment line does
// not run off the side of the code block it is printed in.
function wrapList(names, width = 58) {
  const lines = []
  let line = ''
  for (const name of names) {
    const next = line ? `${line}, ${name}` : name
    if (next.length > width) { lines.push(line); line = name } else line = next
  }
  if (line) lines.push(line)
  return lines.join('\n--   ')
}


// ==========================================
// schemaRepairSql
// The ALTER TABLEs that bring game_settings up to date.
//
// Generated from what the database actually reported rather than
// from a migration file, so it names the columns that are really
// missing and nothing else. Running it twice is an error on the
// second run ("duplicate column name") rather than a no-op,
// which is why the panel's button is the better route - it skips
// what is already there. This text exists for the case where
// somebody would rather run it with wrangler and see it first.
// ==========================================
export function schemaRepairSql(report) {
  const missing = (report && report.missing) || []

  if (!report || !report.readable) {
    return `-- game_settings could not be inspected on this deployment.\n`
         + `--\n`
         + `-- Either LICENSE_DB is not bound, or the table does not exist\n`
         + `-- yet. Run migrations/0003_games.sql first; everything the\n`
         + `-- panel saves lives in the tables it creates.\n`
  }

  if (!missing.length) {
    return `-- game_settings is up to date.\n`
         + `--\n`
         + `-- Every column the panel writes exists in this database, so\n`
         + `-- there is nothing to add. Anything that fails to save from\n`
         + `-- here on is a real error and not a missing migration.\n`
  }

  const migrations = [...new Set(missing.map(column => column.since))]

  return `-- Bring game_settings up to date.
--
-- ${missing.length} column${missing.length === 1 ? ' is' : 's are'} missing from this database:
--   ${wrapList(missing.map(column => column.name))}
--
-- Introduced by: ${migrations.join(', ')}
--
-- Every one of them is nullable with no default, so adding it is
-- a metadata-only change: no row is rewritten, nothing that is
-- already stored moves, and nothing needs a backfill. The panel's
-- "Repair the schema" button runs exactly these statements and
-- skips any that are already applied.
--
-- ONE statement per column: SQLite's ALTER TABLE takes a single
-- ADD COLUMN, and doing them separately means one that fails
-- costs only itself.

${missing.map(column => `ALTER TABLE game_settings ADD COLUMN ${column.name} ${column.type};`).join('\n')}
`
}


// ==========================================
// purgeSeedSql
// Delete every override row a game has, so it can be built again
// from a clean start.
// ==========================================
export function purgeSeedSql(gameId) {
  const id = slug(gameId)

  return `-- Remove every database override for '${id}'.
--
-- After this the game is exactly what config.js says: same name,
-- same logo, same colour, same descriptions, same prices. The
-- game itself is untouched - it is defined in code, and these
-- two tables only ever held changes made on top of it.
--
-- Players, purchases and entitlements are NOT in these tables
-- and are not affected. Those live in game_orders and
-- game_entitlements, and nothing below names them.
--
-- Run both, in this order.
DELETE FROM game_product_overrides WHERE game_id = ${sqlText(id)};
DELETE FROM game_settings          WHERE game_id = ${sqlText(id)};

-- To build the rows again: open TheGod, edit the game, press
-- save. That writes a fresh game_settings row containing only
-- the fields you actually changed. There is no need to INSERT
-- anything by hand, and a hand-written row of NULLs is what you
-- just removed.
`
}


// ==========================================
// productSeedSql
// Price and availability overrides, as SQL.
//
// Built from the STORED ROWS, not from the merged catalogue.
//
// The merged catalogue is Config.js with the rows laid on top, so
// generating from it produced statements that were true of the
// site and false of the table: a product overridden only on price
// came out with enabled = 1 and a sort_order copied from its
// position in the array, neither of which is in the database.
// Pasting that into a second deployment pinned an ordering
// nobody had chosen and turned three NULLs into decisions.
//
// A NULL column here means "no override on this field". It is
// written as NULL rather than omitted, because the ON CONFLICT
// clause has to be able to REMOVE an override that the source
// deployment has removed - otherwise re-running this after
// clearing a price leaves the old one in place.
// ==========================================
export function productSeedSql(gameId, products = [], overrideRows = {}) {
  const id = slug(gameId)
  const rows = overrideRows && typeof overrideRows === 'object' ? overrideRows : {}
  const known = new Set((products || []).map(product => product.id))

  const nullable = value => (value === null || value === undefined ? 'NULL' : value)

  const statements = Object.keys(rows).sort().map(productId => {
    const row = rows[productId] || {}
    // A row for a product id that is not in Config.js is dead
    // weight - Games/Registry.js ignores it, because no shipped
    // client has ever heard of that id - and worth flagging where
    // somebody will see it.
    const orphan = known.has(productId)
      ? ''
      : `-- NOTE: '${productId}' is not in this game's store.products in Config.js.\n`
        + `-- This row is ignored on read. It is either a leftover from a\n`
        + `-- renamed product or a typo.\n`

    return orphan + `INSERT INTO game_product_overrides
  (game_id, product_id, enabled, price_usd, sort_order, badge, updated_at)
VALUES (${sqlText(id)}, ${sqlText(productId)}, ${nullable(row.enabled)}, ${sqlText(row.price_usd)}, ${nullable(row.sort_order)}, ${sqlExact(row.badge)}, ${Number(row.updated_at) || Date.now()})
ON CONFLICT (game_id, product_id) DO UPDATE SET
  enabled = excluded.enabled,
  price_usd = excluded.price_usd,
  sort_order = excluded.sort_order,
  badge = excluded.badge,
  updated_at = excluded.updated_at;`
  })

  if (!statements.length) {
    return `-- No product overrides are stored for '${id}'.\n`
         + `--\n`
         + `-- All ${(products || []).length} product${(products || []).length === 1 ? '' : 's'} `
         + `are being sold exactly as Config.js\n`
         + `-- defines them: same price, same order, same ribbons. That is\n`
         + `-- the state you want unless there is a reason not to, and there\n`
         + `-- is nothing to copy to another deployment.\n`
  }

  return `-- Product overrides for '${id}' — ${statements.length} row${statements.length === 1 ? '' : 's'}.\n`
       + `--\n`
       + `-- NULL means "no override on this field": the value comes from\n`
       + `-- store.products in Config.js. It is written out rather than\n`
       + `-- omitted so that re-running this also REMOVES an override that\n`
       + `-- has since been cleared here.\n\n`
       + statements.join('\n\n') + '\n'
}


// ==========================================
// wranglerSnippet
// The binding entry, ready to paste.
// ==========================================
export function wranglerSnippet(gameId) {
  const names = namesFor(gameId)

  return `    {
      "binding": "${names.binding}",
      "database_name": "${names.database}",
      "database_id": "PASTE_THE_ID_FROM_WRANGLER_D1_CREATE"
    }`
}


// ==========================================
// setupCommands
// Everything to run, in the order it has to be run in.
//
// Options describe what KIND of game this is, because half of
// these steps do not apply to all of them:
//
//   android  false for a browser game - no APK, so no Android
//            OAuth client and no deep-link scheme
//   login    false for a game that never signs anybody in - no
//            Google clients at all, and no redirect URI
//   origin   this deployment's own address, so step 5 prints the
//            line to paste rather than a placeholder
//
// The steps are renumbered after filtering, so "step 4" is
// always the fourth thing to actually do.
// ==========================================
export function setupCommands(gameId, { android = true, login = true, origin = '' } = {}) {
  const names = namesFor(gameId)
  const base = String(origin || '').replace(/\/+$/, '')
  const redirect = base ? `${base}/oauth/callback` : 'https://<your-domain>/oauth/callback'

  const secrets = [
    `npx wrangler secret put ${names.env.web}`,
    `npx wrangler secret put ${names.env.secret}`
  ]
  if (android) secrets.push(`npx wrangler secret put ${names.env.android}`)

  const steps = [
    {
      title: 'Create the database',
      command: `npx wrangler d1 create ${names.database}`,
      note: 'Prints a database_id. Copy it — the next step needs it.'
    },
    {
      title: 'Add the binding',
      command: wranglerSnippet(gameId),
      note: `Paste into the "d1_databases" array in wrangler.jsonc, with the id from step 1.`,
      isFile: true
    },
    {
      title: 'Create the tables',
      command: `npx wrangler d1 execute ${names.database} --remote --file=./migrations/${names.id}.sql`,
      note: 'Save the generated SQL as that file first.'
    },
    login && {
      title: 'Set the OAuth secrets',
      command: secrets.join('\n'),
      note: 'From the Google Cloud console, OAuth 2.0 client IDs. '
          + (android
              ? 'The Android client identifies the APK and needs the signing key\'s SHA-1. '
              : 'A browser game needs no Android client, so there is none here. ')
          + `${names.env.deepLinkScheme} is deliberately NOT on this list: a deep-link scheme is not a `
          + 'secret, it has a fallback in config.js, and the TheGod panel changes it without a deploy.'
    },
    login && {
      title: 'Authorise the redirect URI in Google',
      command: redirect,
      note: 'Google Cloud console ▸ Credentials ▸ your Web client ▸ Authorized redirect URIs. '
          + 'Add one line per hostname this Worker answers on — the custom domain AND the '
          + '*.workers.dev address. A hostname that is missing here is Error 400: redirect_uri_mismatch, '
          + 'and no Worker variable can fix it because the check happens on Google\'s side. '
          + 'The Environment tab of the panel prints the exact lines for this deployment.',
      isFile: true
    },
    android && {
      title: 'Register the deep link in the Unity build',
      command: 'Assets/Plugins/Android/AndroidManifest.xml',
      note: 'The Unity tab generates this file with the right scheme already in it. Without the '
          + 'intent-filter it contains, Android has nowhere to deliver the sign-in code and the '
          + 'browser simply opens a blank tab — with no error anywhere.',
      isFile: true
    },
    {
      title: 'Add the game to the code',
      command: `// paste the generated entry into GAME_REGISTRY in Config.js`,
      note: 'This is the step that makes the game exist. Nothing before it puts a game on the site.',
      isFile: true
    },
    {
      title: 'Deploy',
      command: 'npx wrangler deploy',
      note: 'The game appears on the dashboard the moment this finishes.'
    }
  ].filter(Boolean)

  return steps.map((entry, index) => ({ ...entry, step: index + 1 }))
}


// ==========================================
// productKindHint
// One line explaining what a kind means, for the panel.
//
// Here rather than in the page because the page is a view and
// this is a rule about the data - and because the same sentence
// is wanted in the SQL builder and in the catalogue editor.
// ==========================================
export function productKindHint(kind) {
  switch (kind) {
    case PRODUCT_KIND.CONSUMABLE:
      return 'Spent and bought again. The balance goes up on purchase and down when the game consumes it.'
    case PRODUCT_KIND.PASS:
      return 'Owned for a while. Buying again while one is running extends it rather than restarting it.'
    default:
      return 'Owned once, forever. Buying it twice changes nothing, which is why a double grant is harmless.'
  }
}
