// ==========================================
// Games/Sql.js
// The SQL a new game needs, written by the site rather than by
// hand.
//
// Public exports:
//   slug(value)                       -> a safe game id
//   namesFor(gameId)                  -> binding / database / env names
//   gameSchemaSql(gameId, options)    -> the game's own D1 schema
//   settingsSeedSql(gameId, settings) -> an override row, as SQL
//   productSeedSql(gameId, products)  -> product overrides, as SQL
//   purgeSeedSql(gameId)              -> the DELETEs that clear both
//   wranglerSnippet(gameId)           -> the d1_databases entry
//   setupCommands(gameId, options)    -> the wrangler commands, in order
//
// It does not execute anything. Not against D1, not against
// anything. The output is text on a page with a copy button.
// ==========================================

import { PRODUCT_KIND } from '../Config.js'


// ==========================================
// slug
// A game id that is safe everywhere it has to appear.
// ==========================================
export function slug(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40)
}


// ==========================================
// namesFor
// Every name derived from one game id.
// ==========================================
export function namesFor(gameId) {
  const id = slug(gameId)
  const upper = id.replace(/-/g, '_').toUpperCase()

  return {
    id,
    upper,
    binding: `${upper}_DB`,
    database: `${id}-db`,
    // The Pascal-case form used for a Unity namespace and for
    // the default package name.
    pascal: id.split('-').filter(Boolean).map(part => part[0].toUpperCase() + part.slice(1)).join(''),
    env: {
      android: `${upper}_GOOGLE_CLIENT_ID_ANDROID`,
      web: `${upper}_GOOGLE_CLIENT_ID_WEB`,
      secret: `${upper}_GOOGLE_CLIENT_SECRET`,
      deepLinkScheme: `${upper}_DEEPLINK_SCHEME`
    }
  }
}


// ==========================================
// gameSchemaSql
// One game's own database, complete.
// ==========================================
export function gameSchemaSql(gameId, {
  gameName = '',
  withPurchases = true,
  withSessions = false,
  withSeed = false
} = {}) {
  const names = namesFor(gameId)
  const title = gameName || names.pascal
  const at = new Date().toISOString().slice(0, 10)

  const head = `-- ==========================================
-- ${names.database}
-- The player database for ${title}.
--
-- Generated by the TheGod panel on ${at}.
-- Review it before you run it. Nothing on the site executes
-- this file - that is on purpose, and this comment is the
-- moment it buys you.
--
-- Apply with:
--   npx wrangler d1 create ${names.database}
--   (copy the printed database_id into wrangler.jsonc)
--   npx wrangler d1 execute ${names.database} --remote --file=./migrations/${names.id}.sql
--
-- Every statement is CREATE ... IF NOT EXISTS, so running it
-- twice is a no-op rather than an error.
--
-- Bound in wrangler.jsonc as "${names.binding}", which is the
-- name GAME_REGISTRY['${names.id}'].d1Binding must contain. If
-- those two strings ever disagree, every data endpoint for this
-- game answers "db_not_bound" and nothing else breaks - which
-- is a confusing hour, so they are worth checking first.
-- ==========================================


-- ==========================================
-- players
-- One row per person who has signed in.
--
-- THE COLUMN NAMES BELOW ARE A CONTRACT. worker.js reads them
-- by name in handleDatabaseGet, handleDatabaseSet and
-- handleDatabasePatch, and pages/leaderboard.js reads
-- username / high_score / profile_pic_url. Renaming one here
-- does not produce an error anywhere - it produces a game whose
-- saves quietly stop working.
--
-- The row is created at first sign-in and updated from then on.
-- Nothing deletes it: a player who uninstalls and comes back
-- next year still owns their score.
-- ==========================================
CREATE TABLE IF NOT EXISTS players (
  -- The local part of the Google address, lowercased and cut to
  -- fifteen characters - the same derivation the Worker makes
  -- in playerIdFromEmail(). Short, stable, and readable in a
  -- support thread, which a Google subject id is not.
  player_id       TEXT PRIMARY KEY,

  email           TEXT NOT NULL,

  -- 3-12 characters, English letters and digits only, checked
  -- against a profanity blocklist by validateUsername() in
  -- worker.js before it ever reaches this column.
  username        TEXT,

  profile_pic_url TEXT,

  -- The leaderboard's sort key. Only ever moves up: the write
  -- path refuses a score that is not higher than the one
  -- already here, so a replayed or tampered submission cannot
  -- lower somebody's record.
  high_score      INTEGER NOT NULL DEFAULT 0,

  games_played    INTEGER NOT NULL DEFAULT 0,
  total_play_time INTEGER NOT NULL DEFAULT 0,

  -- Cosmetics the game owns the meaning of. selected_color is a
  -- bare hex string ('FFFFFF'); the two purchased_* columns are
  -- JSON, read with a fallback so a malformed value is an empty
  -- inventory rather than a 500.
  selected_color  TEXT NOT NULL DEFAULT 'FFFFFF',
  purchased_colors TEXT NOT NULL DEFAULT '["FFFFFF"]',
  purchased_items  TEXT NOT NULL DEFAULT '{}',

  -- Anything else THIS game wants to save.
  --
  -- A JSON object the Worker stores, merges and never inspects.
  -- The columns above are the ones this side reads by name - the
  -- leaderboard needs high_score, the account page needs
  -- total_play_time - and this is for everything it does not
  -- need to understand.
  --
  -- That is what keeps a new game from needing a schema change:
  -- levelsCompleted, an inventory, unlocked characters, a
  -- difficulty setting - all of it is a key in here rather than
  -- a column, a Worker mapping and a C# field.
  --
  --   PATCH  { "dataPatch": { "levelsCompleted": 12 } }   merges
  --   POST   { "data":      { ... whole document ... } }  replaces
  data_json        TEXT NOT NULL DEFAULT '{}',

  created_at      INTEGER NOT NULL,
  last_login      INTEGER,

  -- Moderation. NULL everywhere means an ordinary account.
  --
  -- banned_at is permanent until lifted; restricted_until is the
  -- time-boxed version and needs no clearing, because a value in
  -- the past is simply not a restriction. The state shown in the
  -- panel is derived from these two, so there is no third column
  -- that can disagree with them.
  --
  -- worker.js reads banned_at on every score submission and both
  -- leaderboard queries. A game whose table lacks these columns
  -- still works - every check falls back to "not banned" - which
  -- is what migrations/0006_player_moderation.sql exists to fix
  -- for games created before this block did.
  banned_at        INTEGER,
  ban_reason       TEXT,
  restricted_until INTEGER,
  restrict_reason  TEXT,
  admin_note       TEXT
);

-- The leaderboard query, which is the only hot read in this
-- database: ORDER BY high_score DESC LIMIT n, run on every
-- board view.
CREATE INDEX IF NOT EXISTS idx_players_score ON players (high_score DESC);
CREATE INDEX IF NOT EXISTS idx_players_email ON players (email);

-- The board query is "highest scores, excluding banned", so the
-- index carries both columns.
CREATE INDEX IF NOT EXISTS idx_players_active_score ON players (banned_at, high_score DESC);`

  const purchases = `


-- ==========================================
-- player_purchases
-- This game's own copy of what a player owns.
--
-- The authoritative record lives in the licence database's
-- game_entitlements table, which is what
-- GET /games/${names.id}/entitlements reads. This table is a
-- mirror, and it exists for one reason: a game that has to make
-- a network call before it can draw the shop is a game that
-- shows a spinner on a train.
--
-- Written when the client syncs, read freely, and never trusted
-- over the entitlements API when the two disagree - the API is
-- the side that saw the money.
-- ==========================================
CREATE TABLE IF NOT EXISTS player_purchases (
  player_id   TEXT NOT NULL,

  -- The catalogue id from GAME_REGISTRY['${names.id}'].store,
  -- not the Google Play sku. The two are allowed to differ and
  -- usually do.
  product_id  TEXT NOT NULL,

  -- 'consumable' | 'nonconsumable' | 'pass'
  kind        TEXT NOT NULL DEFAULT 'nonconsumable',

  -- Unspent balance for a consumable; 1 for anything owned
  -- outright.
  quantity    INTEGER NOT NULL DEFAULT 0,

  -- 'web' (bought on the site), 'in-app' (bought in the store),
  -- 'grant' (given by an operator).
  source      TEXT NOT NULL DEFAULT 'web',

  expires_at  INTEGER,
  synced_at   INTEGER NOT NULL,

  PRIMARY KEY (player_id, product_id),
  FOREIGN KEY (player_id) REFERENCES players (player_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_purchases_player ON player_purchases (player_id);`

  const sessions = `


-- ==========================================
-- play_sessions
-- One row per run, for playtime and retention.
--
-- Optional, and genuinely optional: nothing in the Worker reads
-- it. It is here because total_play_time on the players table
-- is a single number that can only ever answer "how long", and
-- the questions that follow the first week are all "when" and
-- "how often".
--
-- Rows are cheap and numerous. Prune them on a schedule if this
-- game gets busy - the aggregate on players survives the prune.
-- ==========================================
CREATE TABLE IF NOT EXISTS play_sessions (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id  TEXT NOT NULL,
  started_at INTEGER NOT NULL,
  ended_at   INTEGER,
  duration   INTEGER NOT NULL DEFAULT 0,
  score      INTEGER NOT NULL DEFAULT 0,
  app_version TEXT
);

CREATE INDEX IF NOT EXISTS idx_sessions_player ON play_sessions (player_id, started_at);`

  const seed = `


-- ==========================================
-- A row to prove the table works.
--
-- Delete it once you have seen it on the leaderboard. It is
-- here because "did the migration run?" is otherwise answered
-- by an empty table, which looks exactly like a migration that
-- did not.
-- ==========================================
INSERT OR IGNORE INTO players
  (player_id, email, username, high_score, games_played, created_at, last_login)
VALUES
  ('demo', 'demo@example.com', 'DemoPlayer', 1, 1, ${Date.now()}, ${Date.now()});`

  return head
    + (withPurchases ? purchases : '')
    + (withSessions ? sessions : '')
    + (withSeed ? seed : '')
    + '\n'
}


// ==========================================
// sqlText
// A string literal SQLite will accept.
// ==========================================
function sqlText(value) {
  if (value === null || value === undefined || value === '') return 'NULL'
  return "'" + String(value).replace(/'/g, "''") + "'"
}


// ==========================================
// settingsSeedSql
// The current overrides, as a statement somebody can run on
// another deployment.
//
// The point is a staging site and a live one that look the
// same. Without this, matching them means retyping every field
// into a second panel and hoping.
// ==========================================
export function settingsSeedSql(gameId, settings = {}) {
  const id = slug(gameId)
  const at = Date.now()

  const columns = [
    ['display_name', sqlText(settings.display_name)],
    ['logo_url', sqlText(settings.logo_url)],
    ['accent_color', sqlText(settings.accent_color)],
    ['desc_fa', sqlText(settings.desc_fa)],
    ['desc_en', sqlText(settings.desc_en)],
    ['desc_ja', sqlText(settings.desc_ja)],
    ['tags_json', sqlText(settings.tags_json)],
    ['status', sqlText(settings.status)],
    ['download_enabled', settings.download_enabled === null || settings.download_enabled === undefined
      ? 'NULL'
      : (Number(settings.download_enabled) ? '1' : '0')],
    ['download_json', sqlText(settings.download_json)],
    ['min_version', sqlText(settings.min_version)],
    ['note', sqlText(settings.note)],
    ['deeplink_scheme', sqlText(settings.deeplink_scheme)],

    // The landing page (0005 and 0008). Carried across with
    // everything else, because a staging site that matches the
    // live one on prices and not on its screenshots is not a
    // staging site - it is a second game page to maintain.
    ['hero_url', sqlText(settings.hero_url)],
    ['videos_json', sqlText(settings.videos_json)],
    ['devices_json', sqlText(settings.devices_json)],
    ['about_fa', sqlText(settings.about_fa)],
    ['about_en', sqlText(settings.about_en)],
    ['about_ja', sqlText(settings.about_ja)],
    ['tagline_fa', sqlText(settings.tagline_fa)],
    ['tagline_en', sqlText(settings.tagline_en)],
    ['tagline_ja', sqlText(settings.tagline_ja)],
    ['features_json', sqlText(settings.features_json)],
    ['screenshots_json', sqlText(settings.screenshots_json)],
    ['faq_json', sqlText(settings.faq_json)]
  ]

  // Every value NULL means there is no override to carry
  // anywhere - the game is running entirely on Config.js. An
  // INSERT of thirteen NULLs is not a useful thing to paste into
  // another deployment, and reading one is genuinely confusing:
  // it looks like a row that says something when it says
  // nothing. So say that instead, and offer the DELETE that
  // removes the row rather than an INSERT that recreates it
  // empty.
  const set = columns.filter(([, value]) => value !== 'NULL')

  if (!set.length) {
    return `-- '${id}' has no overrides. Every column in its game_settings row\n`
         + `-- is NULL, which means the site is showing exactly what\n`
         + `-- GAME_REGISTRY in config.js says - the name, the logo, the\n`
         + `-- colour, the descriptions, all of it.\n`
         + `--\n`
         + `-- There is nothing to copy to another deployment: a row of\n`
         + `-- NULLs and no row at all render identically. If you want the\n`
         + `-- empty row gone, this is the statement that does it, and the\n`
         + `-- panel writes a fresh one the next time you press save.\n`
         + `--\n`
         + `-- DELETE FROM game_settings WHERE game_id = ${sqlText(id)};\n`
  }

  // Only the columns that are actually SET are named. Two
  // reasons, and the second is the one that bites: naming a NULL
  // column adds nothing, and naming a column the target database
  // does not have yet - a deployment that stopped at 0005 - fails
  // the whole statement over a field that was empty anyway.
  const names = set.map(([name]) => name)

  return `-- Overrides for '${id}', as they stand right now.
-- Safe to re-run: the ON CONFLICT clause updates in place.
--
-- Only the fields that are actually set appear below. Everything
-- not named here is "no override" and comes from Config.js.
INSERT INTO game_settings
  (game_id, ${names.join(', ')}, updated_at)
VALUES (
  ${sqlText(id)},
${set.map(([, value]) => `  ${value}`).join(',\n')},
  ${at}
)
ON CONFLICT (game_id) DO UPDATE SET
${names.map(name => `  ${name} = excluded.${name}`).join(',\n')},
  updated_at = excluded.updated_at;
`
}


// ==========================================
// purgeSeedSql
// Delete every override row a game has, so it can be built again
// from a clean start.
// ==========================================
export function purgeSeedSql(gameId) {
  const id = slug(gameId)

  return `-- Remove every database override for '${id}'.
--
-- After this the game is exactly what config.js says: same name,
-- same logo, same colour, same descriptions, same prices. The
-- game itself is untouched - it is defined in code, and these
-- two tables only ever held changes made on top of it.
--
-- Players, purchases and entitlements are NOT in these tables
-- and are not affected. Those live in game_orders and
-- game_entitlements, and nothing below names them.
--
-- Run both, in this order.
DELETE FROM game_product_overrides WHERE game_id = ${sqlText(id)};
DELETE FROM game_settings          WHERE game_id = ${sqlText(id)};

-- To build the rows again: open TheGod, edit the game, press
-- save. That writes a fresh game_settings row containing only
-- the fields you actually changed. There is no need to INSERT
-- anything by hand, and a hand-written row of NULLs is what you
-- just removed.
`
}


// ==========================================
// productSeedSql
// Price and availability overrides, as SQL.
// ==========================================
export function productSeedSql(gameId, products = []) {
  const id = slug(gameId)
  const at = Date.now()

  const rows = products
    .filter(product => Array.isArray(product.overrides) && product.overrides.length > 0)
    .map(product => `INSERT INTO game_product_overrides
  (game_id, product_id, enabled, price_usd, sort_order, badge, updated_at)
VALUES (${sqlText(id)}, ${sqlText(product.id)}, ${product.enabled === false ? 0 : 1}, ${sqlText(product.priceUsd)}, ${Number(product.sortOrder) || 0}, ${sqlText(product.badge)}, ${at})
ON CONFLICT (game_id, product_id) DO UPDATE SET
  enabled = excluded.enabled,
  price_usd = excluded.price_usd,
  sort_order = excluded.sort_order,
  badge = excluded.badge,
  updated_at = excluded.updated_at;`)

  if (!rows.length) {
    return `-- No product overrides are set for '${id}'.\n`
         + `-- Everything is being sold at the price in config.js, which is\n`
         + `-- the state you want unless there is a reason not to.\n`
  }

  return `-- Product overrides for '${id}'.\n` + rows.join('\n\n') + '\n'
}


// ==========================================
// wranglerSnippet
// The binding entry, ready to paste.
// ==========================================
export function wranglerSnippet(gameId) {
  const names = namesFor(gameId)

  return `    {
      "binding": "${names.binding}",
      "database_name": "${names.database}",
      "database_id": "PASTE_THE_ID_FROM_WRANGLER_D1_CREATE"
    }`
}


// ==========================================
// setupCommands
// Everything to run, in the order it has to be run in.
//
// Options describe what KIND of game this is, because half of
// these steps do not apply to all of them:
//
//   android  false for a browser game - no APK, so no Android
//            OAuth client and no deep-link scheme
//   login    false for a game that never signs anybody in - no
//            Google clients at all, and no redirect URI
//   origin   this deployment's own address, so step 5 prints the
//            line to paste rather than a placeholder
//
// The steps are renumbered after filtering, so "step 4" is
// always the fourth thing to actually do.
// ==========================================
export function setupCommands(gameId, { android = true, login = true, origin = '' } = {}) {
  const names = namesFor(gameId)
  const base = String(origin || '').replace(/\/+$/, '')
  const redirect = base ? `${base}/oauth/callback` : 'https://<your-domain>/oauth/callback'

  const secrets = [
    `npx wrangler secret put ${names.env.web}`,
    `npx wrangler secret put ${names.env.secret}`
  ]
  if (android) secrets.push(`npx wrangler secret put ${names.env.android}`)

  const steps = [
    {
      title: 'Create the database',
      command: `npx wrangler d1 create ${names.database}`,
      note: 'Prints a database_id. Copy it — the next step needs it.'
    },
    {
      title: 'Add the binding',
      command: wranglerSnippet(gameId),
      note: `Paste into the "d1_databases" array in wrangler.jsonc, with the id from step 1.`,
      isFile: true
    },
    {
      title: 'Create the tables',
      command: `npx wrangler d1 execute ${names.database} --remote --file=./migrations/${names.id}.sql`,
      note: 'Save the generated SQL as that file first.'
    },
    login && {
      title: 'Set the OAuth secrets',
      command: secrets.join('\n'),
      note: 'From the Google Cloud console, OAuth 2.0 client IDs. '
          + (android
              ? 'The Android client identifies the APK and needs the signing key\'s SHA-1. '
              : 'A browser game needs no Android client, so there is none here. ')
          + `${names.env.deepLinkScheme} is deliberately NOT on this list: a deep-link scheme is not a `
          + 'secret, it has a fallback in config.js, and the TheGod panel changes it without a deploy.'
    },
    login && {
      title: 'Authorise the redirect URI in Google',
      command: redirect,
      note: 'Google Cloud console ▸ Credentials ▸ your Web client ▸ Authorized redirect URIs. '
          + 'Add one line per hostname this Worker answers on — the custom domain AND the '
          + '*.workers.dev address. A hostname that is missing here is Error 400: redirect_uri_mismatch, '
          + 'and no Worker variable can fix it because the check happens on Google\'s side. '
          + 'The Environment tab of the panel prints the exact lines for this deployment.',
      isFile: true
    },
    android && {
      title: 'Register the deep link in the Unity build',
      command: 'Assets/Plugins/Android/AndroidManifest.xml',
      note: 'The Unity tab generates this file with the right scheme already in it. Without the '
          + 'intent-filter it contains, Android has nowhere to deliver the sign-in code and the '
          + 'browser simply opens a blank tab — with no error anywhere.',
      isFile: true
    },
    {
      title: 'Add the game to the code',
      command: `// paste the generated entry into GAME_REGISTRY in Config.js`,
      note: 'This is the step that makes the game exist. Nothing before it puts a game on the site.',
      isFile: true
    },
    {
      title: 'Deploy',
      command: 'npx wrangler deploy',
      note: 'The game appears on the dashboard the moment this finishes.'
    }
  ].filter(Boolean)

  return steps.map((entry, index) => ({ ...entry, step: index + 1 }))
}


// ==========================================
// productKindHint
// One line explaining what a kind means, for the panel.
//
// Here rather than in the page because the page is a view and
// this is a rule about the data - and because the same sentence
// is wanted in the SQL builder and in the catalogue editor.
// ==========================================
export function productKindHint(kind) {
  switch (kind) {
    case PRODUCT_KIND.CONSUMABLE:
      return 'Spent and bought again. The balance goes up on purchase and down when the game consumes it.'
    case PRODUCT_KIND.PASS:
      return 'Owned for a while. Buying again while one is running extends it rather than restarting it.'
    default:
      return 'Owned once, forever. Buying it twice changes nothing, which is why a double grant is harmless.'
  }
}
